server:
  addr: "127.0.0.1"
  port: "80"
  openProxy: true
proxy:
  addr: "127.0.0.1"
  port: "7890"
chatConn:
  timeout: 20
  idleConnTimeout: 168
logSet:
  logFilePath: "./config/log/"
  logFileName: "log.log"
